parameters:
    cart.security.interactive_login_listener.class: CSF\CartBundle\Listener\GestionUtilisateurListener
    cart.commande.controller.class: CSF\CartBundle\Controller\CommandeController
    cart.gestion.filter_controller_event.class: CSF\CartBundle\Listener\GestionCartListener
services:
   handle.commande:
      class: CSF\CartBundle\Model\HandleCommande
      arguments: [@doctrine.orm.entity_manager, @security.context]
   handle.commande.session:
      class: CSF\CartBundle\Model\HandleCommandeSession
      arguments: [@doctrine.orm.entity_manager, @session]
   cart.handle:
      class: CSF\CartBundle\Model\CartHandleCommande
      arguments: [@handle.commande.session, @session]
   
      
   cart.security.interactive_login_listener:
      class: %cart.security.interactive_login_listener.class%
      arguments: [@session]
      tags:
            -  { name: kernel.listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
   cart.gestion.filter_controller_event:
      class: %cart.gestion.filter_controller_event.class%
      tags:
            -  { name: kernel.listener, event: core.controller, method: onCoreController }